name: CI-ubuntu-test2
on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # every day at JPT 9:05 13:05 17:05 21:05=UTC 0:05,...  ## GHC using UTC timezone
   # - cron: "0 */6 * * *"  # every xx hour
   # - cron: "*/60 * * * *"  #every xx minute
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ubuntu-test2.yml'
      - 'config/ubuntu-test2-release.flag'
  pull_request:
  workflow_dispatch:  

concurrency: # when running cancel last job
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout server tools
      uses: actions/checkout@v4
      with:
        repository: GitsopHQ/ServerTools
        token: ${{ secrets.GH_PAT }} 
        path: .
    - name: Install server tools
      run: bash ./ubuntu-ssh/install.sh
      env:
        N_TOKEN: ${{ secrets.N_TOKEN }}  
        V_TOKEN: ${{ secrets.V_TOKEN }}          
    - name: Start
      run: bash ./ubuntu-ssh/start.sh
